
package mdp.register.terminal.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TestSoapService", targetNamespace = "http://test.mdp")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestSoapService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "resultReturn", targetNamespace = "http://test.mdp")
    @RequestWrapper(localName = "result", targetNamespace = "http://test.mdp", className = "mdp.register.terminal.client.Result")
    @ResponseWrapper(localName = "resultResponse", targetNamespace = "http://test.mdp", className = "mdp.register.terminal.client.ResultResponse")
    public String result();

}
