
package mdp.register.terminal.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TestSoapServiceService", targetNamespace = "http://test.mdp", wsdlLocation = "http://localhost:8080/MDP_Projekat_22_Web/services/TestSoapService?wsdl")
public class TestSoapServiceService
    extends Service
{

    private final static URL TESTSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSOAPSERVICESERVICE_EXCEPTION;
    private final static QName TESTSOAPSERVICESERVICE_QNAME = new QName("http://test.mdp", "TestSoapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MDP_Projekat_22_Web/services/TestSoapService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSOAPSERVICESERVICE_WSDL_LOCATION = url;
        TESTSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public TestSoapServiceService() {
        super(__getWsdlLocation(), TESTSOAPSERVICESERVICE_QNAME);
    }

    public TestSoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSOAPSERVICESERVICE_QNAME, features);
    }

    public TestSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTSOAPSERVICESERVICE_QNAME);
    }

    public TestSoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSOAPSERVICESERVICE_QNAME, features);
    }

    public TestSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestSoapService
     */
    @WebEndpoint(name = "TestSoapService")
    public TestSoapService getTestSoapService() {
        return super.getPort(new QName("http://test.mdp", "TestSoapService"), TestSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestSoapService
     */
    @WebEndpoint(name = "TestSoapService")
    public TestSoapService getTestSoapService(WebServiceFeature... features) {
        return super.getPort(new QName("http://test.mdp", "TestSoapService"), TestSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw TESTSOAPSERVICESERVICE_EXCEPTION;
        }
        return TESTSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
