version: '3'

volumes:
  mdp_redis_data:
    external: true
  mdp_rabbitmq_data:
    external: true

services:
  redis:
    restart: unless-stopped
    image: redislabs/redismod
    ports:
      - 6379:6379
  redisinsight:
    restart: unless-stopped
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - mdp_redis_data:/db
  rabbitmq:
    restart: unless-stopped
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=client
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - mdp_rabbitmq_data:/var/lib/rabbitmq/
