
package mdp.register.terminals.client;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://terminals.register.mdp")
public class TerminalNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TerminalNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TerminalNotFoundException_Exception(String message, TerminalNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TerminalNotFoundException_Exception(String message, TerminalNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: mdp.register.terminals.client.TerminalNotFoundException
     */
    public TerminalNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
